#!/bin/sh

# Compiles all files in this package.

javac -g -deprecation -d .. -classpath ../sss.jar:.. -Xlint:unchecked *.java ast/*.java 2>/tmp/err || less /tmp/err

cp grammar.sss ../org/sc3d/apt/crazon/compiler/
