var TEST_CODE = (
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    'WINDOW WINDOW "R" GET 0.01 + SET(R) ; WAIT ; ' +
    ''
);
